### ISSUE TITLE
Is open-channel emulation currently possible?

### ISSUE THREAD

**Issue by sooyun802** [SimpleSSD/SimpleSSD-FullSystem#1]
Hi,

I am trying to use SimpleSSD to emulate an open-channel SSD device.

Your website mentions that open-channel SSD modeling will be provided in SimpleSSD 2.0 (Amber).
Does the current released version (v2.0.1: SimpleSSD FullSystem version 2.0.1.) provide open-channel SSD modeling as well?

Thanks.

**Comment by kukdh1** [comment]
Hi,

Yes, you can use Open-Channel SSD with current version.

Prepare Linux Kernel with `lightnvm` and `pblk` module.
Run gem5 with `--ssd-interface=ocssd` option.

Check [wiki page](https://github.com/SimpleSSD/SimpleSSD-FullSystem/wiki/Running-instructions) of this repository for running instructions.
The instruction is based on v1.1, but v2.0 should work with same command line.

Thanks.
