### ISSUE TITLE
Where is simplessd in gem5 Full System model？

### ISSUE THREAD

**Issue by cyb3727** [SimpleSSD/SimpleSSD-FullSystem#1]
After I compile the SimpleSSD-FullSystem， and then I start it. I use m5term to connect it. But I do not know where is SimpleSSD? How I use the SimpleSSD，Can you tell me? thanks!

This the details information: 
compiling command:
scons build/X86/gem5.opt
running command: 
build/X86/gem5.opt configs/example/fs.py --kernel=x86_64-vmlinux-2.6.22.9.smp --disk-image=linux-x86.img --SSDConfig=sample_cfg/config.cfg

**Comment by SimpleSSD** [comment]
Sorry, the email notification was turn off on this repo.

You may want to check [here](http://simplessd.yonsei.ac.kr/fs.html) for more details.
If you have more question, please comment here.

Thanks.
