### ISSUE TITLE
alternative to m5term or disabling "too much work for irq4" message?

### ISSUE THREAD

**Issue by shehbazj** [SimpleSSD/SimpleSSD-FullSystem#11]
### Running Environment (please complete the following information):
 - Host OS and Kernel version: Linux (none) 4.9.92
 - Compiler version used to build SimpleSSD-FullSystem: gcc (Ubuntu 5.4.0-6ubuntu1~16.04.11) 5.4.0
 - SimpleSSD-FullSystem version: v2.1.0
 - Guest Kernel version: [e.g. Linux 4.14 compiled with aarch64-linux-gnu-gcc]
 - Compiler version used to build Guest Kernel binary: [x86root.img]

### Execution information
- Execution command line of gem5:
./build/X86/gem5.opt ./configs/example/fs.py --kernel=x86_64-vmlinux-4.9.92 --num-cpu=4 --cpu-clock=2GHz --caches --l2cache --cpu-type=AtomicSimpleCPU --mem-size=3GB --mem-type=DDR4_2400_8x8  --ssd-interface=nvme --ssd-config=src/dev/storage/simplessd/config/sample.cfg --disk-image=x86root.img
- Execution command line in guest OS (inside of simulation):
up arrow

### Explain what you want to ask here:
Thank you for making your project open source. my question:
This is probably an artifact of gem5, I get the following error multiple times which is due to UART interrupts:
`serial8250: too much work for irq4`
Is there a way to disable these messages? I am connecting to guest using m5term, is there another way to connect to SimpleSSD?

Thank you in advance.

**Comment by kukdh1** [comment]
Hi,

That problem comes from UART hardware of x86 gem5.
You can ask gem5 maintainers to fix the problem (or search not-yet-merged gem5 patch from [gem5-review](https://gem5-review.googlesource.com/)).
Or simply disable `printk` function of 8250 serial driver in Linux Kernel.

Thanks.
