### ISSUE TITLE
build problem on ubuntu -gcc 9.3

### ISSUE THREAD

**Issue by alinezhad2018** [SimpleSSD/SimpleSSD-FullSystem#15]
### Running Environment (please complete the following information):
Ubuntu 
GCC  9.3

*/*/simplessd-fullsystem# git show -s HEAD
commit 96377cf409f1bc10d8b5678221f1aa16b1cb0d06 (HEAD -> master, tag: v2.0.10, origin/master, origin/HEAD)
Author: Donghyun Gouk <kukdh1@gmail.com>
Date:   Sat Apr 4 04:19:42 2020 +0900

*/*/simplessd-fullsystem# cd src/dev/storage/simplessd/
*/*/simplessd-fullsystem/src/dev/storage/simplessd# git show -s HEAD
commit 73ad8ad5220ce5ebfeb055687d0328765a046c0f (HEAD, tag: v2.0.13)
Author: Donghyun Gouk <kukdh1@gmail.com>
Date:   Sun Feb 2 02:16:25 2020 +0900

    Release SimpleSSD version 2.0.13
### Explain what you want to ask here:
when try to build this error is appear: 

TypeError: argument should be integer or bytes-like object, not 'str':
  File "/*/*/simplessd-fullsystem/SConstruct", line 357:
    main['GCC'] = CXX_version and CXX_version.find('g++') >= 0

IS not support this version of GCC???

**Comment by kukdh1** [comment]
Hi,

The error message is coming from scons (python) not GCC.
Please use python version 2.7 not 3.x, because gem5 v19 does not support python 3.
(gem5 v20 supports python 3, but I did not merged them to `SimpleSSD-FullSystem`)

Thanks.
