### ISSUE TITLE
run a simple program on full-system simplessd

### ISSUE THREAD

**Issue by alinezhad2018** [SimpleSSD/SimpleSSD-FullSystem#16]
Hi
when I run this command, it took a lot of time and the "stats.txt" and "debug.txt" were empty!

./build/X86/gem5.opt --debug-flag=DMA --debug-file=debug_DMA.txt ./configs/example/fs.py --kernel=x86_64-vmlinux-4.9.92 --num-cpu=3 --cpu-clock=4GHz --caches --l2cache --cpu-type=AtomicSimpleCPU --mem-size=3GB --mem-type=DDR4_2400_8x8 --ssd-interface=nvme --ssd-config=./src/dev/storage/simplessd/config/sample.cfg --disk-image=x86root.img 

how can I run a simple program on a full-system SimpleSSD, using fs.py , with NVMe config 
which command should I run?

**Comment by kukdh1** [comment]
Hi,

You need to attach terminal (`m5term`) to gem5. See [here](http://www.gem5.org/documentation/general_docs/fullsystem/m5term) .

For the expected boot time, see [here](https://docs.simplessd.org/en/v2.0.12/matrix.html).

Thanks.

**Comment by alinezhad2018** [comment]
Thank you for your reply.
I use terminal, but I am not sure which commands will send some requests (read or write) to the storage system.
because the number of read/write on NVMe always the same at the stats.txt file.
1- which command do you suggest? 
2- how can I check which requests (detail information about the request: type of request, starting address of request, size of request, ...) have been send to the NVMe interface?
3- which parameters in stats.txt file use for evaluating the performance of storage systems?

**Comment by kukdh1** [comment]
Hi,

Please check #17.

Thanks.
