### ISSUE TITLE
find out which requests have been sent to the storage system?

### ISSUE THREAD

**Issue by alinezhad2018** [SimpleSSD/SimpleSSD-FullSystem#17]
hi,

 when we run a simplessd as a full-system, Is it possible to check which requests have been sent  to the storage systems (simpleSSD standalone)?
in which part of codes the information about the requests (which are send to the storage system =simplessd) could be find?

Regards,

**Comment by kukdh1** [comment]
Hi,

This should be help.
https://docs.simplessd.org/en/v2.0.12/instructions/analyze.html

Thanks.

**Comment by kukdh1** [comment]
P.S. You can use `fio` or other popular disk performance measurement tools (which can run on Linux) as you are running full-system simulation.

**Comment by alinezhad2018** [comment]
thank you very much for your response.
and how can I check which requests have been send to the storage systems?(in which part of code these information is available to maybe print out for check?)
