### ISSUE TITLE
Question : in which part of the code the I/O requests are send to the storage system?

### ISSUE THREAD

**Issue by alinezhad2018** [SimpleSSD/SimpleSSD-FullSystem#18]
hi

 Thank you for your support on this open-source full-system simulator,
I am looking for a specific part of code (file) where I can access to the parameters related to the I/O requests  (type:write or read, size of requests, ...).
I want to check which requests are send to the storage System, for example NVMe Interface.

thanks

**Comment by kukdh1** [comment]
Hi,

Please check `src/dev/storage/simplessd/hil/nvme/namespace.cc`.
There are functions named `flush`, `write`, and `read`.

You can find `debugprint` function:
```c++
  debugprint(LOG_HIL_NVME,
             "NVM     | WRITE | SQ %u:%u | CID %u | NSID %-5d | %" PRIX64
             " + %d",
             req.sqID, req.sqUID, req.entry.dword0.commandID, nsid, slba, nlb);
```

As NVMe can have multiple namespaces, `HIL` object is stored in `NVMe::Subsystem`, not NVMe::`Namespace`.
By invoking `pParent->write()`, NVMe can issue write request to underlying HIL. (`pParent` is pointer to `NVMe::Subsystem`)

Attach debugger should be better to understand the code execution flow.

Thanks.
