### ISSUE TITLE
Is there any benchmark which is affected the storage system have been already run with Amber?

### ISSUE THREAD

**Issue by alinezhad2018** [SimpleSSD/SimpleSSD-FullSystem#19]
Hi,

I could run different fio commands on Amber, but as the fio commands directly send to the storage system, we couldn't check the effect of other parts of system (such as memory, cache and so on) on the performance of storage system.
I wonder if you have run any specific benchmark which is send some requests to the storage system (interactive with storage part of system) on Amber?

Regards,

**Comment by kukdh1** [comment]
Hi,

You can any kinds of workloads (such as database, web server) that can be run on conventional Linux on gem5.
(You may need to cross-compile them if you using ARM arch.)

Even docker runs on gem5, you can freely selects the workload.

Thanks.
