### ISSUE TITLE
problem run a fullsystem with ARM

### ISSUE THREAD

**Issue by alinezhad2018** [SimpleSSD/SimpleSSD-FullSystem#20]
Hi,

I could run Amber with X86 correctly and run some script (fio) on it.
but when I try to run the same things on ARM it require username and password to login to the guest OS ().
 so I couldn't run my script on it.

./build/ARM/gem5.opt   ./configs/example/fs-arm.py --kernel=aarch64-vmlinux-4.9.92 --dtb-file=armv8_gem5_v1_4cpu.dtb --machine-type=VExpress_GEM5_V1  --num-cpu=1 --cpu-clock=3GHz --caches --l2cache --cpu-type=AtomicSimpleCPU --mem-size=1GB --mem-type=DDR4_2400_8x8 --ssd-interface=nvme --ssd-config=./src/dev/storage/simplessd/config/sample.cfg  --disk-image=linaro-aarch64-linux.img 

I wonder if there is any specific config for ARM which I should consider? 
could you share me any commands with ARM, which already have been run as a full-system.

![error-ARM-fs](https://user-images.githubusercontent.com/39709452/94658810-9be20c00-0303-11eb-9190-d7d56e9a079e.png)

**Comment by kukdh1** [comment]
Hi

Try `root` as account name.
Shell will appear without asking password.

Thanks.
