### ISSUE TITLE
Question about Amber paper (parameters bandwidth and latency in Amber simulator)

### ISSUE THREAD

**Issue by sac2019** [SimpleSSD/SimpleSSD-FullSystem#21]
Hi,

I studied the Amber paper, and try to work with Amber simulator
but I couldn't find out which parameters in  output results of Amber simulator are related to the bandwidth and latency which are reported in Fig 8 and Fig.9 of Amber paper.
I means which parameters from stats file stands for these to evaluation terms(latency and bandwidth)

Thanks

**Comment by kukdh1** [comment]
Hi,

Bandwidth and latency values are reported by `fio`, not in stat file.
You need to run full-system and execute `fio` on NVMe block device.
Result will be printed out to `stdout`.

Thanks.
