### ISSUE TITLE
page swap support?

### ISSUE THREAD

**Issue by sac2019** [SimpleSSD/SimpleSSD-FullSystem#22]
hi,

I wonder if this full system simulator support the page swap and virtual memory or not?
is there any information in output file related to them? for example the number of page fault or number or page swap memory?

**Comment by sac2019** [comment]
Hi,

I try to run a simple program which generating page fault (major fault) but nothing (read/write request) send to the storage part!

**Comment by kukdh1** [comment]
Hi,

I didn't tried the swap partition, please ask gem5 community for the support.

Or, you can try with following step:
1. Create disk image ([see here](https://docs.simplessd.org/en/v2.0.12/tips/disk.html))
2. Create partition table and swap partition
3. Boot with IDE disk.
4. Configure swap partition with `swapon` command. (If command not exists, build it manually)
5. Check that page swapping occurs.

Thanks.
