### ISSUE TITLE
Data path in SimpleSSD

### ISSUE THREAD

**Issue by minmin20028** [SimpleSSD/SimpleSSD-FullSystem#25]
### Running Environment (please complete the following information):
 - Host OS and Kernel version: [e.g. Ubuntu 16.04 with Linux 4.14]
 - Compiler version used to build SimpleSSD-FullSystem: [e.g. GCC 4.8.5]
 - SimpleSSD-FullSystem version: [e.g. v2.0.3 - or commit hash]
 - SimpleSSD version: [e.g. v2.0.4 - or commit hash]
 - Guest Kernel version: [e.g. Linux 4.14 compiled with aarch64-linux-gnu-gcc]
 - Compiler version used to build Guest Kernel binary: [e.g. Linaro GCC 7.2.1]

### Execution information
- Execution command line of gem5:
[e.g. ./build/ARM/gem5.opt ./configs/common/fs.py --kernel=...]
- Execution command line in guest OS (inside of simulation):
[e.g. ./fio --direct=1 --ioengine=libaio ...]

### Explain what you want to ask here:
A clear explanation of your question.

Hi,
Thanks for your open-source work.

I`m trying to implement or study ECC(error correcting code) in SSD Controlloer data-path with SimpleSSD.
In order to do this, I think it`s necessary to look at the data itself (which i read/write with nvme-cli).
But I wonder where the part that points to the data itself in SimpleSSD code.
Also, i want to know the flow of data in the process of read and write.

thanks.

**Comment by kukdh1** [comment]
Hi,

This answer is based on your e-mail.

> 1. User data representation in SimpleSSD.

SimpleSSD stores data in raw disk format if you enabled disk image feature in configuration file.
This makes convenient use of existing disk images (like gem5 images) -- you can use such disk images directly with SimpleSSD.
And such file I/O is handled by HIL (namespace).

SipmleSSD does not support physical data serialization/deserialization as this feature is only used for NAND level research.
To access data at specific NAND page, there are two options:
1. Add feature to read/write data for each NAND page from/to file.
2. At the PAL, perform reverse address translation to get logical address of current page, and read page from disk image.

> 2. Data flow

As written in first section, SimpleSSD only handles data at HIL level.
But, if you want to know which codes/functions handles I/O, just create breakpoint at PAL and check the call stack.
As most part of current SimpleSSD is functional (only HIL is event-driven), you can check all the routines by looking at stack.

Thanks.
