### ISSUE TITLE
Error when building in ARM mode

### ISSUE THREAD

**Issue by kimbob13** [SimpleSSD/SimpleSSD-FullSystem#3]
Hello,
I've tried to build SimpleSSD in ARM mode as you recommended in [previous reply](https://github.com/SimpleSSD/SimpleSSD-FullSystem/issues/2), but I encoutred another problem.

Below picture is shown when I try to do `scons build/ARM/gem5.opt -j 4`
![2018-06-12 2 28 16](https://user-images.githubusercontent.com/26755098/41272015-6e3b6b58-6e4e-11e8-9223-879299cf543b.png)

It seems there is an error in ARM related code.
If you need more information about my environment, please let me know.

Thanks!

**Comment by kukdh1** [comment]
Hi,

Maybe you are using GCC 7.x.
Please use GCC version 6.x or less.
gem5 has problem with GCC 7.x

Thanks.
