### ISSUE TITLE
Failed to read SimpleSSD configuration

### ISSUE THREAD

**Issue by RuixiangMa** [SimpleSSD/SimpleSSD-FullSystem#4]
Hi,
I have installed the SimpleSSD-FullSystem, when I run build/X86/gem5.opt configs/example/fs.py, "Aborted (core dumped)" occurs. Then, I debug it with gdb,  the error information is:../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
Did you have similar problems? how to solve this problem?
Thanks for your reply!

**Comment by kukdh1** [comment]
Hi,

I've never seen such error.

You may want to check how to run [gem5](http://gem5.org),
And [SimpleSSD-FullSystem](https://simplessd.org/fs.html).

Thanks.

P.S. Content of current [SimpleSSD homepage](https://simplessd.org) is outdated, and we are plan to update homepage until Sep. 2018.

**Comment by RuixiangMa** [comment]
Thanks for your reply! I try to run it  with ARM architecture, error information is as follows:

gem5 Simulator System.  http://gem5.org
gem5 is copyrighted software; use the --copyright option for details.
gem5 compiled Jul 24 2018 09:03:14
gem5 started Jul 25 2018 01:06:32
gem5 executing on ubuntu, pid 2160
command line: ./build/ARM/gem5.opt configs/example/fs.py

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/simplessd/SimpleSSD-FullSystem-release/src/python/m5/main.py", line 435, in main
    exec filecode in scope
  File "configs/example/fs.py", line 374, in <module>
    test_sys = build_test_system(np, simplessd)
  File "configs/example/fs.py", line 111, in build_test_system
    security=options.enable_security_extensions)
  File "/home/simplessd/SimpleSSD-FullSystem-release/configs/common/FSConfig.py", line 412, in makeArmSystem
    self.realview.attachPciDevice(
  File "/home/simplessd/SimpleSSD-FullSystem-release/src/python/m5/SimObject.py", line 1130, in __getattr__
    raise AttributeError, err_string
AttributeError: object 'VExpress_EMM' has no attribute 'attachPciDevice'
  (C++ object is not yet constructed, so wrapped C++ methods are unavailable.)
