### ISSUE TITLE
Is there any way to extend size of linux Kernel?

### ISSUE THREAD

**Issue by ray5273** [SimpleSSD/SimpleSSD-FullSystem#5]
I've tried to test a benchmark using fio in simplessd kernel.
But when I tried to random/seq write in simulator, there's an error shows not enough space left on device. 
So, I tried several ways to fix this problems, but all things didn't work.
Can you tell me how to expand the size of simplessd kernel? 
![SimpleSSD_seqwrite_sata_2](https://user-images.githubusercontent.com/8529112/54529875-79f49300-49c4-11e9-9f02-e20f1d99bea5.PNG)

**Comment by kukdh1** [comment]
Hi,

I assume you want to create larger disk image for storing some big files, not the Linux Kernel.
Please check the [SimpleSSD homepage](https://docs.simplessd.org/tips/disk.html) for creating new disk image for gem5 simulator.

Thanks.
