### ISSUE TITLE
Does SimpleSSD-FullSystem support Gem5's checkpoint-restore?

### ISSUE THREAD

**Issue by moonkyung** [SimpleSSD/SimpleSSD-FullSystem#6]
Hi,

I'm trying to use gem5's checkpoint-restore, but gem5 abort as following:
![image](https://user-images.githubusercontent.com/13434962/58525185-c7cc1980-8205-11e9-8757-a8b1f472f081.png)

Does SimpleSSD-FullSystem support gem5's checkpoint-restore?

Thanks.

**Comment by kukdh1** [comment]
Hi,

Currently (v2.0.x), checkpoint is not supported.
I'm working on v2.1, which will support checkpointing.

Thanks.
