### ISSUE TITLE
multi-core out or order does not work

### ISSUE THREAD

**Issue by kazi-zubair** [SimpleSSD/SimpleSSD-FullSystem#8]
### Running Environment (please complete the following information):
 - Host OS and Kernel version: [Ubuntu 16.04 with Linux 4.12]
 - GCC 5.4

### Execution information
- build/X86/gem5.opt configs/example/fs.py --checkpoint-dir=chk/ --disk-image=/home/kazi/simplessd/SimpleSSD-FullSystem/files/disks/d2b.img --kernel=/home/kazi/simplessd/SimpleSSD-FullSystem/files/binaries/vmlinux --mem-size=16GB --cpu-type=DerivO3CPU --mem-type=DDR4_2400_4x16 --ssd-interface=nvme --ssd-config=./src/dev/storage/simplessd/config/sample.cfg --caches -n 4

### Explain what you want to ask here:

Running simplessd in our of order mode gives me this error

gem5.opt: build/X86/cpu/o3/regfile.cc:142: void PhysRegFile::initFreeList(UnifiedFreeList*): Assertion `intRegIds[reg_idx].index() == reg_idx' failed.

If I use just one core (-n 1) then this error is not there. How to simulate multicore out of order processor with simplessd?

**Comment by kukdh1** [comment]
Hi,

*"This is gem5 problem, so please ask to gem5 community."*

The current gem5 version that SimpleSSD uses has bug on O3 CPU.
I try to maintain gem5 up-to-date but several gem5 versions I tried recently failed to boot with Timing/InOrder/O3 CPU.

If you found specific version of gem5 (with commit has) which O3 CPU works,
I can provide patch to connect SimpleSSD to gem5.

Thanks.
