### ISSUE TITLE
Modify code to simulate SSD Read/Writes without fio benchmark

### ISSUE THREAD

**Issue by ray5273** [SimpleSSD/SimpleSSD-FullSystem#9]
### Running Environment (please complete the following information):
 - Host OS and Kernel version: [e.g. Ubuntu 16.04 with Linux 4.14] Ubuntu 16.04 with Linux 5.0.0
 - Compiler version used to build SimpleSSD-FullSystem: [e.g. GCC 4.8.5] GCC 4.8.5
 - SimpleSSD-FullSystem version: [e.g. v2.0.3 - or commit hash] 2.0.5
 - SimpleSSD version: [e.g. v2.0.4 - or commit hash]
 - Guest Kernel version: [e.g. Linux 4.14 compiled with aarch64-linux-gnu-gcc]
  x86_64-Vmlinux 4.9.92
 - Compiler version used to build Guest Kernel binary: [e.g. Linaro GCC 7.2.1]

### Execution information
- Execution command line of gem5:
[e.g. ./build/ARM/gem5.opt ./configs/common/fs.py --kernel=...]
./build/X86/gem5.opt --debug-flag=M5Print --debug-file=debug.txt ./configs/example/fs.py --kernel=x86_64-vmlinux-4.9.92 --num-cpu=1 --cpu-clock=3.6GHz --caches --l2cache --cpu-type=AtomicSimpleCPU --mem-size=3GB --mem-type=DDR4_2400_8x8 --ssd-interface=nvme --ssd-config=./src/dev/storage/simplessd/config/sample.cfg

- Execution command line in guest OS (inside of simulation):
[e.g. ./fio --direct=1 --ioengine=libaio ...]
No Command line

### Explain what you want to ask here:
Hello, I'm trying to generate SSD Read/Write execution in simulation without using fio benchmark program.

My questions are below:
1. Is it possible to generate SSD Read/Write inside of simulation with adding SimObject or modifying code in SimpleSSD?

2. If answer of first question is possible, where is the proper position of additional codes? 
(ex) src/dev/storage/simplessd , or need to add directory)

3. If answer of first question is impossible, is there any way to add custom I/O using C or C++ language code in kernel file ?

**Comment by kukdh1** [comment]
Hi,

It looks like you don't need full-system environment.
You can use standalone version to generate synthesized I/O or replaying trace file.

Thanks.
